#!/usr/bin/env -S cargo +nightly -Zscript
---cargo
[package]
name = "setup-cross"
edition = "2024"

[dependencies]
ureq = { version = "2", features = ["tls"] }
anyhow = "1"
tar = "0.4"
xz2 = "0.1"
---

//! Sets up cross-compilation for macOS and Linux via cargo-zigbuild.
//!
//! Run: `cargo +nightly -Zscript scripts/setup-cross.rs`
//!
//! Assumes `cargo-zigbuild` is already installed. Does NOT install zig —
//! cargo-zigbuild locates its own zig. This script only:
//!   - adds rustup targets for darwin + linux (x86_64 + aarch64)
//!   - downloads the macOS SDK into ./tools/ (needed by objc2-app-kit)
//!   - writes tools/env.sh and tools/env.ps1 with SDKROOT

use anyhow::{Context, Result, bail};
use std::fs;
use std::io::{self, Read};
use std::path::{Path, PathBuf};
use std::process::Command;

const MACOS_SDK_URL: &str =
    "https://github.com/joseluisq/macosx-sdks/releases/download/14.0/MacOSX14.0.sdk.tar.xz";
const MACOS_SDK_NAME: &str = "MacOSX14.0.sdk";

const RUST_TARGETS: &[&str] = &[
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
];

fn main() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf();
    let tools = root.join("tools");
    fs::create_dir_all(&tools)?;

    ensure_zigbuild()?;
    println!("host: {}", std::env::consts::OS);

    add_rust_targets()?;
    let sdk_dir = install_macos_sdk(&tools)?;
    write_env(&tools, &sdk_dir)?;

    println!();
    println!("done. Next: `just check-macos` (after sourcing tools/env.sh or tools/env.ps1)");
    Ok(())
}

fn ensure_zigbuild() -> Result<()> {
    if which("cargo-zigbuild").is_none() {
        bail!("cargo-zigbuild not found; install it with `cargo install cargo-zigbuild`");
    }
    Ok(())
}

fn add_rust_targets() -> Result<()> {
    for t in RUST_TARGETS {
        println!("[rustup] target add {t} (stable)");
        // `cargo +nightly -Zscript` exports RUSTUP_TOOLCHAIN=nightly to child
        // processes, which would cause rustup to install targets into nightly
        // instead of the stable toolchain the user actually builds with.
        let status = Command::new("rustup")
            .env_remove("RUSTUP_TOOLCHAIN")
            .args(["target", "add", "--toolchain", "stable", t])
            .status()
            .context("failed to run rustup")?;
        if !status.success() {
            bail!("rustup target add {t} failed");
        }
    }
    Ok(())
}

fn install_macos_sdk(tools: &Path) -> Result<PathBuf> {
    let sdk_dir = tools.join(MACOS_SDK_NAME);
    if sdk_dir.exists() {
        println!("[sdk] already present: {}", sdk_dir.display());
        return Ok(sdk_dir);
    }

    println!("[sdk] downloading {MACOS_SDK_URL}");
    let bytes = download(MACOS_SDK_URL)?;
    println!("[sdk] extracting ({} MiB)", bytes.len() / (1024 * 1024));
    extract_tar_xz(&bytes, tools)?;
    println!("[sdk] installed at {}", sdk_dir.display());
    Ok(sdk_dir)
}

fn write_env(tools: &Path, sdk_dir: &Path) -> Result<()> {
    let sh = format!(
        "# Generated by scripts/setup-cross.rs — source before cross-compiling.\n\
         export SDKROOT=\"{}\"\n",
        sdk_dir.display(),
    );
    fs::write(tools.join("env.sh"), sh)?;

    let ps1 = format!(
        "# Generated by scripts/setup-cross.rs — dot-source before cross-compiling.\r\n\
         $env:SDKROOT = \"{}\"\r\n",
        sdk_dir.display(),
    );
    fs::write(tools.join("env.ps1"), ps1)?;

    println!("[env] wrote tools/env.sh and tools/env.ps1");
    Ok(())
}

fn download(url: &str) -> Result<Vec<u8>> {
    let resp = ureq::get(url)
        .call()
        .with_context(|| format!("GET {url}"))?;
    let mut buf = Vec::new();
    resp.into_reader().read_to_end(&mut buf)?;
    Ok(buf)
}

fn extract_tar_xz(bytes: &[u8], dest: &Path) -> Result<()> {
    let dec = xz2::read::XzDecoder::new(io::Cursor::new(bytes));
    let mut archive = tar::Archive::new(dec);
    archive.set_preserve_permissions(false);
    archive.set_overwrite(true);

    for entry in archive.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.into_owned();
        if cfg!(windows) && path_has_invalid_windows_chars(&path) {
            continue;
        }
        if let Err(e) = entry.unpack_in(dest) {
            // Skip symlink/hardlink failures on Windows (common in SDK tarballs).
            if cfg!(windows) && e.kind() == io::ErrorKind::PermissionDenied {
                continue;
            }
            return Err(e.into());
        }
    }
    Ok(())
}

fn path_has_invalid_windows_chars(path: &Path) -> bool {
    path.to_string_lossy()
        .chars()
        .any(|c| matches!(c, ':' | '*' | '?' | '<' | '>' | '|' | '"')
            // Drive letter colon at position 1 is fine, but relative tar paths
            // never have one, so any ':' is bad.
        )
}

fn which(bin: &str) -> Option<PathBuf> {
    let exe = if cfg!(windows) {
        format!("{bin}.exe")
    } else {
        bin.to_string()
    };
    std::env::var_os("PATH")?
        .to_string_lossy()
        .split(if cfg!(windows) { ';' } else { ':' })
        .map(|p| Path::new(p).join(&exe))
        .find(|p| p.is_file())
}
